;  ____        _          _   _  __          ____      _            
; / ___| _ __ (_) ___ ___| |_(_)/ _|_   _   / ___|___ | | ___  _ __ 
; \___ \| '_ \| |/ __/ _ | __| | |_| | | | | |   / _ \| |/ _ \| '__|
;  ___) | |_) | | (_|  __| |_| |  _| |_| | | |__| (_) | | (_) | |   
; |____/| .__/|_|\___\___|\__|_|_|  \__, |  \____\___/|_|\___/|_|   
;       |_|                         |___/          
;                 

;  [  ] Autor : Darkz(darrkzz)
;  [  ] Github : @darrkzz

[Graphite]
accent             = F2F2F2
accent-active      = A0A0A0
accent-inactive    = 3C3C3C
banner             = 1E1E1E
border-active      = D0D0D0
border-inactive    = 3F3F3F
header             = 2A2A2A
highlight          = 3C3C3C
main               = 1E1E1E
notification       = 3C3C3C
notification-error = 3C3C3C
subtext            = A0A0A0
text               = F2F2F2