#  ____                         __ _ _         ____                 _     _ _       
# / ___| _   _ _ __   ___ _ __ / _(_| | ___   / ___|_ __ __ _ _ __ | |__ (_| |_ ___ 
# \___ \| | | | '_ \ / _ | '__| |_| | |/ _ \ | |  _| '__/ _` | '_ \| '_ \| | __/ _ \
#  ___) | |_| | |_) |  __| |  |  _| | |  __/ | |_| | | | (_| | |_) | | | | | ||  __/
# |____/ \__,_| .__/ \___|_|  |_| |_|_|\___|  \____|_|  \__,_| .__/|_| |_|_|\__\___|
#             |_|                                            |_|                    
#

#  [  ] Autor : Darkz(darrkzz)
#  [  ] Github : @darrkzz

[theme]
name = "Graphite Dark"
author = "Darkz"

[colors]
background = "#1E1E1E"            # Fundo principal
foreground = "#D0D0D0"            # Texto/UI
selection_background = "#3C3C3C"  # Realce / Seleção
selection_foreground = "#F2F2F2"  # Texto selecionado
highlight = "#505050"             # Hover / Destaques
border = "#3F3F3F"                # Bordas e divisores

[colors.normal]
black   = "#1E1E1E"  # Fundo
red     = "#7A7A7A"  # Vermelho apagado (substituto)
green   = "#7F8F7A"  # Verde morto
yellow  = "#8A815F"  # Amarelo envelhecido
blue    = "#6E6E8F"  # Azul dessaturado
magenta = "#8B7E8F"  # Magenta morto
cyan    = "#7C8F8F"  # Ciano esmaecido
white   = "#D0D0D0"  # Texto padrão

[colors.bright]
black   = "#2A2A2A"  # Fundo secundário
red     = "#A0A0A0"  # Texto secundário
green   = "#A5B5A0"  # Verde pálido
yellow  = "#B5A580"  # Amarelo pálido
blue    = "#A0A0C0"  # Azul pálido
magenta = "#C0A0C0"  # Magenta claro
cyan    = "#A0C0C0"  # Ciano claro
white   = "#F2F2F2"  # Texto claro
